services:
  # PHP-FPM контейнер
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./database:/var/www/html/database
      - ./.env_docker:/var/www/html/.env
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost
    networks:
      laravel_network:
        aliases:
          - app
          - laravel_app

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - laravel_network

  # PerfectWorld (Go) сервис в той же сети
  perfectworld:
    image: alpine:3.20
    container_name: perfectworld
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /root/perfectworld:/app:ro
    command: ["/app/perfectworld"]
    expose:
      - "8080"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
